In [ ]:
# DeepfusionMOT 설치

%cd /content/drive/MyDrive/workspace/study/3D_Object_detection
!git clone https://github.com/wangxiyang2022/DeepFusionMOT

In [ ]:
# 필요 모듈 설치

%cd /data/NIA50/50-2/models/DeepFusionMOT
!pip install -r requirements.txt

In [8]:
# 디텍팅
# main.py와 visualization에서 경로 수정 필수

%cd /data/NIA50/50-2/models/DeepFusionMOT
!python main.py

/data/NIA50/50-2/models/DeepFusionMOT
--------------Start processing the Suwon_A_2210261635_0000 dataset--------------
/data/NIA50/50-2/models/DeepFusionMOT/tracking/cost_function.py:32: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 1d, A), array(float64, 1d, C))
  return 0.5 * np.abs(np.dot(x, np.roll(y, 1)) - np.dot(y, np.roll(x, 1)))
[[1154.44690591  572.98392068]
 [1147.58389062  575.37953766]
 [1159.66062542  577.26826025]
 [1166.44949037  574.83287722]
 [1151.88700452  615.66363245]
 [1145.0761149   618.48642336]
 [1156.99163428  620.70284026]
 [1163.7305247   617.83382983]]
[[1154.44690591  572.98392068]
 [1147.58389062  575.37953766]
 [1159.66062542  577.26826025]
 [1166.44949037  574.83287722]
 [1151.88700452  615.66363245]
 [1145.0761149   618.48642336]
 [1156.99163428  620.70284026]
 [1163.7305247   617.83382983]]
[[1312.80353294  567.61873074]
 [1325.79560083  570.31744841]
 [1333.74851057  568.83753399]
 [1320.74834685  566.174

In [ ]:
# 디텍팅 결과 영상 생성
# img_to_video.py 수정 필수

%cd /content/drive/MyDrive/workspace/study/3D_Object_detection/DeepFusionMOT/visualization
!python img_to_video.py